### ISSUE TITLE
A mod is using the deprecated config registration method

### ISSUE THREAD

**Issue by Serega007RU** [embeddedt/ArchaicFix#32]
On the latest version of FalsePatterLib (0.10.10), it throws this error in the logs
```
[23:09:35] [main/WARN]: A mod is using the deprecated config registration method! The following exception contains the stacktrace.
java.lang.Exception
	at com.falsepattern.lib.config.ConfigurationManager.registerConfig(ConfigurationManager.java:114) [ConfigurationManager.class:?]
	at org.embeddedt.archaicfix.asm.ArchaicMixinPlugin.<init>(ArchaicMixinPlugin.java:19) [ArchaicMixinPlugin.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_301]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_301]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_301]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_301]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_301]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:579) [SpongeMixins.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.selectConfigs(MixinTransformer.java:608) [SpongeMixins.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:570) [SpongeMixins.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [SpongeMixins.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [SpongeMixins.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [SpongeMixins.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:310) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:207) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_301]
	at net.minecraft.launchwrapper.LaunchClassLoader.loadClass(LaunchClassLoader.java:95) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_301]
	at net.minecraft.launchwrapper.LaunchClassLoader.loadClass(LaunchClassLoader.java:90) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_301]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_301]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-lib-1.0.10-SNAPSHOT.jar:?]
```

Full log
[latest.log](https://github.com/embeddedt/ArchaicFix/files/9551604/latest.log)

**Comment by embeddedt** [comment]
This is intended. I use the old API to preserve compatibility with FalsePattern 0.9 for those who still use it. There should be no adverse effects to gameplay.
