### ISSUE TITLE
"java.lang.RuntimeException: fastutil was not loaded correctly"

### ISSUE THREAD

**Issue by syndicate25** [embeddedt/ArchaicFix#36]
Made sure threaded chunk updates were not enabled, since I have both Optifine and Fastcraft.

I also tried removing one/both of those mods and attempted to load the game.  Same issue, so they were added back in.

See full log attached.  Snippet of error portion pasted below.

java.lang.RuntimeException: fastutil was not loaded correctly
    at org.embeddedt.archaicfix.helpers.FastutilHelper.checkLoad(FastutilHelper.java:34)
    at org.embeddedt.archaicfix.ArchaicFix.onConstruct(ArchaicFix.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3093)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

[fml-client-latest.log](https://github.com/embeddedt/ArchaicFix/files/9594335/fml-client-latest.log)

**Comment by quentin452** [comment]
try deleting mixingasm, spongemixin and add gastation https://github.com/FalsePattern/GasStation

**Comment by quentin452** [comment]
download archaic fix dev build

**Comment by makamys** [comment]
> FalsePatternLib library downloading has been disabled in the config, and the library is not present on disk! Requested by mod: archaicfix

Actually it appears to be just a configuration problem. Make sure `ENABLE_LIBRARY_DOWNLOADS` is set to `true` in `falsepatternlib.cfg`.

**Comment by syndicate25** [comment]
> try deleting mixingasm, spongemixin and add gastation https://github.com/FalsePattern/GasStation

GasStation is already in the pack.


> > FalsePatternLib library downloading has been disabled in the config, and the library is not present on disk! Requested by mod: archaicfix
> 
> Actually it appears to be just a configuration problem. Make sure `ENABLE_LIBRARY_DOWNLOADS` is set to `true` in `falsepatternlib.cfg`.

doh.  I'll give this a shot right now.  I didn't see that message. . thank you.

**Comment by syndicate25** [comment]
Looks like that (almost) fixed it.  There was a problem with it loading using Triangulator, so I removed that and it's working.

As a side question - any plans to upload this to CF?  If not.. can I request this be added to the approved third party mods on CF?

**Comment by embeddedt** [comment]
> A quick test and wow, my frames more than doubled. This is a lifesaver for 1.7.10. 

Awesome!

> There was a problem with it loading using Triangulator, so I removed that and it's working.

Do you have a crash log? They should work together.

> As a side question - any plans to upload this to CF? If not.. can I request this be added to the approved third party mods on CF?

Yes, eventually. The main reason I haven't uploaded it to CF is that once I do so, people will stop using the development builds, and then I will have to make more frequent releases. Alternative, I could publish each development build as a beta version on CF. I also currently have a lot less time to work on MC than I did in the summer, so updates will be slow unless something absolutely does not work.

I always assumed that anyone could request a mod to be third-party approved. If I need to do that myself, please let me know and I'll look into it. The license already permits usage in modpacks.

**Comment by syndicate25** [comment]
> I always assumed that anyone could request a mod to be third-party approved. If I need to do that myself, please let me know and I'll look into it. The license already permits usage in modpacks.

I'm sure I can request it, I just find it respectful to ask. I didn't know what your plans were with it before now, so I figure it's the best way to go about it.  I'm about to push an update out on this, so it looks like it might have to wait for the next pack update to include ArchaicFix, but I'll personally use it in the meantime.

> Do you have a crash log? They should work together.

I created a fresh crash and log and attached them here.  Attached the crash report just in case you don't need to go through the whole log, and vice versa.

[fml-client-latest.log](https://github.com/embeddedt/ArchaicFix/files/9595136/fml-client-latest.log)
[crash-2022-09-18_13.45.26-client.txt](https://github.com/embeddedt/ArchaicFix/files/9595137/crash-2022-09-18_13.45.26-client.txt)

**Comment by syndicate25** [comment]
> Alternative, I could publish each development build as a beta version on CF. 

If that's not a huge pain for you, that would be amazing.

**Comment by embeddedt** [comment]
@syndicate25 Does the crash happen if you use ArchaicFix and Triangulator, but not Serene Seasons?

**Comment by syndicate25** [comment]
> @syndicate25 Does the crash happen if you use ArchaicFix and Triangulator, but not Serene Seasons?

Yes, it does.  However it does not crash when I only remove Triangulator, but keep Serene Seasons.

[crash-2022-09-18_14.02.49-client.txt](https://github.com/embeddedt/ArchaicFix/files/9595159/crash-2022-09-18_14.02.49-client.txt)

**Comment by embeddedt** [comment]
You know what.. I think Triangulator is depending on an unreleased API. I assume you are using 0.3.0. I will release 0.3.1 in the next few minutes.

**Comment by syndicate25** [comment]
> You know what.. I think Triangulator is depending on an unreleased API. I assume you are using 0.3.0. I will release 0.3.1 in the next few minutes.

Yes I am using 0.3.0.  I'll give the new one a go when it's uploaded :)

**Comment by embeddedt** [comment]
> next few minutes

This will take longer than anticipated due to needing to fix issues after updating to FalsePattern's latest build script.

**Comment by embeddedt** [comment]
Once approved:

https://www.curseforge.com/minecraft/mc-mods/archaicfix/files/3995951

**Comment by syndicate25** [comment]
> Once approved:
> 
> https://www.curseforge.com/minecraft/mc-mods/archaicfix/files/3995951

Greatly appreciate this!  Thank you!
