### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SegoItCh** [embeddedt/ArchaicFix#48]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/15/22 4:19 AM
Description: Initializing game

java.lang.RuntimeException: fastutil was not loaded correctly
	at org.embeddedt.archaicfix.helpers.FastutilHelper.checkLoad(FastutilHelper.java:34)
	at org.embeddedt.archaicfix.ArchaicFix.onConstruct(ArchaicFix.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.embeddedt.archaicfix.helpers.FastutilHelper.checkLoad(FastutilHelper.java:34)
	at org.embeddedt.archaicfix.ArchaicFix.onConstruct(ArchaicFix.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 334002152 bytes (318 MB) / 1617428480 bytes (1542 MB) up to 3797417984 bytes (3621 MB)
	JVM Flags: 1 total; -Xmx4074M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 120 mods loaded, 120 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UC	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	OpenEye{0.8} [OpenEye] (OpenEye-1.7.10-0.8.jar) 
	UC	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UC	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UC	tickDynamic{0.1.5} [Tick Dynamic] (minecraft.jar) 
	UC	tnt_utilities_core{1.2} [TNTUtils Core] (minecraft.jar) 
	UC	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UC	spongemixins{1.5.0} [SpongeMixins] (00gasstation-mc1.7.10-0.3.5.jar) 
	UC	mixingasm{0.2.2} [Mixingasm] (00gasstation-mc1.7.10-0.3.5.jar) 
	UC	mixinbooterlegacy{1.1.2} [MixinBooterLegacy] (00gasstation-mc1.7.10-0.3.5.jar) 
	UC	gasstation{0.3.5} [GasStation] (00gasstation-mc1.7.10-0.3.5.jar) 
	UC	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UC	animatedplayer{1.5.1} [Animated Player Mod] (AnimatedPlayer-1.7.10-1.5.1.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UC	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UC	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UC	falsepatternlib{0.10.13} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.10.13.jar) 
	UE	archaicfix{0.3.3} [Archaic Fix] (archaicfix-mc1.7.10-0.3.3.jar) 
	UC	armoroverlay{2.0} [Armor Overlay] (Armor Overlay 2.0.jar) 
	UC	armorchroma{1.2} [Armor Chroma] (armorchroma-1.2-1.7.10.jar) 
	UC	autopickup{2.1} [AutoPickup] (AutoPickup-1.7.10-2.1.jar) 
	UC	AutoSapling{1.0} [AutoSapling] (AutoSapling-1.1.jar) 
	UC	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UC	backpacks16840{3.5.8} [Backpacks!] (backpacks 1.7.10 - 3.5.8.jar) 
	UC	betterburning{0.4.2} [Better Burning] (BetterBurning-1.7.10-0.4.2.jar) 
	UC	bettersprinting{2.3.0} [Better Sprinting] (BetterSprinting-1.7.10-v2.3.0.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UC	birdsfoods{3.1 - [1.7.10]} [Bird's Foods] (birdsfoods-1.7.10 - 3.1.jar) 
	UC	birdsnests{1.4} [Bird's Nests] (BirdsNests1.7.10-1.4.jar) 
	UC	BuildCraft|Core{7.1.24} [BuildCraft] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Builders{7.1.24} [BC Builders] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Robotics{7.1.24} [BC Robotics] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Silicon{7.1.24} [BC Silicon] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Energy{7.1.24} [BC Energy] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Transport{7.1.24} [BC Transport] (buildcraft-7.1.24.jar) 
	UC	BuildCraft|Factory{7.1.24} [BC Factory] (buildcraft-7.1.24.jar) 
	UC	campfirebackport{1.7.10-1.10} [Campfire Backport] (campfirebackport-1.7.10-1.10.jar) 
	UC	chococraft{4.5.8} [ChocoCraft Plus] (ChocoCraftPlus-1.7.10-4.5.8.jar) 
	UC	chunkpregenerator{2.5.0} [Chunk Pregenerator] (Chunk Pregenerator-V1.7.10-2.5.3.jar) 
	UC	ChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator-MC1.7.10-1.0.1.jar) 
	UC	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-1.7.10-release-2.1.0-lts.21-universal.jar) 
	UC	controlling{7.0.0} [Controlling] (Controlling-1.7.10-1.0.0.3.jar) 
	UC	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UC	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UC	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UC	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UC	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UC	craftingtweaks{1.0.88} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.88.jar) 
	UC	craftpresence{1.9.3} [CraftPresence] (CraftPresence-Forge-1.7.10-Release-1.9.3.jar) 
	UC	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
	UC	customcrosshairmod{0.8.3} [Custom Crosshair Mod] (crosshairmod-v0.8.3-forge-mc1.7.10.jar) 
	UC	Ding{MC1.7.10v2} [Ding] (Ding-MC1.7.10v2.jar) 
	UC	egg-auto-hatch{1.3} [Egg Auto Hatch] (egg-auto-hatch-1.3-mc-1.7.jar) 
	UC	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UC	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UC	falsetweaks{2.0.0-beta0003} [FalseTweaks] (falsetweaks-mc1.7.10-2.0.0-beta0003.jar) 
	UC	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UC	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UC	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UC	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.7.10-1.3.0b.jar) 
	UC	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UC	Growthcraft{1.7.10-2.7.2} [Growthcraft] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Cellar{1.7.10-2.7.2} [Growthcraft Cellar] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Apples{1.7.10-2.7.2} [Growthcraft Apples] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Bamboo{1.7.10-2.7.2} [Growthcraft Bamboo] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Bees{1.7.10-2.7.2} [Growthcraft Bees] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Fishtrap{1.7.10-2.7.2} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Grapes{1.7.10-2.7.2} [Growthcraft Grapes] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Hops{1.7.10-2.7.2} [Growthcraft Hops] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Milk{1.7.10-2.7.2} [Growthcraft Milk] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	Growthcraft|Rice{1.7.10-2.7.2} [Growthcraft Rice] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UC	industrialupgrade{2.5.21} [Industrial Upgrade] (IndustrialUpgrade-2.5.21.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UC	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	ironfurnaces{1.2.4} [Iron Furnaces] (ironfurnaces-1.2.4R.jar) 
	UC	jaff{1.4.2_for_1.7.10} [Just a Few Fish] (JustAFewFish-1.4.2_for_1.7.10.jar) 
	UC	lootbags{2.0.17} [Loot Bags] (LootBags-1.7.10-2.0.17.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UC	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UC	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UC	moveplus{v2.3.1} [Move Plus] (moveplus-2.3.1 for MC v1.7.10.jar) 
	UC	AS_MultiMine{1.4.3} [Multi Mine] (MultiMine-1.7.10.jar) 
	UC	overloadedarmorbar{1.0.0} [Overloaded Armor Bar] (overloadedarmorbar-1.7.10-1.0.0.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	RTG{1.7.10-1.1.1.7} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.7.jar) 
	UC	sampler{1.60.1} [Sampling Performance Profiler] (sampler-1.60.1.jar) 
	UC	sereneseasons{1.2.18} [Serene Seasons] (SereneSeasons-1.7.10-1.2.18.jar) 
	UC	shouldersurfing{2.2.3} [Shoulder Surfing] (ShoulderSurfing-1.7.10-2.2.3.jar) 
	UC	smithing{1.7.10-1.1.0} [Smithing In The "90'S"] (SmithingInThe90'S-1.7.10-1.1.0.jar) 
	UC	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UC	SpecialMobs{3.2.2} [Special Mobs] (SpecialMobs-1.7.10-3.2.2.jar) 
	UC	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UC	stepup{1.0.1-mc1.7.10} [StepUp] (StepUp-1.0.1-mc1.7.10.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UC	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	UC	tipthescales{1.0.1} [TipTheScales] (TipTheScales-1.7.10-3.0.0.2.jar) 
	UC	tnt_utilities{1.2} [TNTUtils] (tnt_utilities-mc1.7.10-1.2.jar) 
	UC	trashslot{1.0.31} [TrashSlot] (trashslot-mc1.7.10-1.0.31.jar) 
	UC	tumbleweed{1.7.10-0.2} [Tumbleweed] (tumbleweed-1.7.10-0.2.jar) 
	UC	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UC	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UC	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UC	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UC	XaeroMinimapFair{21.10.27} [Xaero's Minimap] (Xaeros_Minimap_FP21.10.27_Forge_1.7.10.jar) 
	UC	XaeroWorldMap{1.14.1.20} [Xaero's World Map] (XaerosWorldMap_1.14.1.20_Forge_1.7.10.jar) 
	UC	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 522.25' Renderer: 'NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10 Minecraft Forge 1.7.10-10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 522.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by embeddedt** [comment]
Please send the full log, but it sounds like FalsePatternLib failed to download a library. This might be fixable by removing the `falsepattern` folder in your `.minecraft` directory.

**Comment by SegoItCh** [comment]
Still crashing
[latest.log](https://github.com/embeddedt/ArchaicFix/files/9790910/latest.log)

**Comment by embeddedt** [comment]
@FalsePattern Any idea why this might occur?

**Comment by FalsePattern** [comment]
This is an undocumented architecture issue that i've also encountered, basically, invoking the library downloader inside any mixin code causes the library loading to either hang, or the library just doesn't get inserted. This is due to a bug with how SpongePowered Mixins hooks into the classloader's data.

**Comment by embeddedt** [comment]
Hmm, would it help to move the library download to an FML setup hook then?

**Comment by FalsePattern** [comment]
My solution inside falsetweaks was to just move the library loading from the mixin plugin to the static initializer of my coremod class ([permalink](https://github.com/FalsePattern/FalseTweaks/blob/7485991dd8ead86c68578f7f132ee7d2f78ef723/src/main/java/com/falsepattern/falsetweaks/CoreLoadingPlugin.java#L34)), because coremod constructors run extremely early.

**Comment by embeddedt** [comment]
Should be fixed in 0.3.4.
